obstacle_range: 4.0
raytrace_range: 4.0
robot_radius: 0.35

observation_sources: laser_scan_sensor
transform_tolerance : 2.0
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
