TrajectoryPlannerROS:

# Robot Configuration Parameters
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 1.0
  max_vel_x: 0.2
  min_vel_x: 0.1
  max_vel_theta:  0.5 
  min_vel_theta:  -0.5
  min_in_place_vel_theta: 0.12
  escape_vel: -0.05
  holonomic_robot: false

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.30
  xy_goal_tolerance: 0.20
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 0.6
  sim_granularity: 0.025
  vx_samples: 5
  vtheta_samples: 20
  controller_frequency: 5

# Trajectory Scoring Parameters
  meter_scoring: true
  path_distance_bias: 0.6
  goal_distance_bias: 0.8
  occdist_scale: 0.1
  dwa: false
