DWAPlannerROS:

# Robot Configuration Parameters
  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_th: 2.0
  max_vel_trans:  0.18
  min_vel_trans:  0.08
  max_vel_x: 0.18
  min_vel_x: 0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 0.5
  min_vel_theta: 0.12

# Goal Tolerance Parametes
  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

# Forward Simulation Parameters
  sim_time: 1.0
  sim_granularity: 0.05
  vx_samples: 20
  vy_samples: 0
  vth_samples: 60
  controller_frequency: 5.0

# Trajectory Scoring Parameters
  path_distance_bias: 40.0
  goal_distance_bias: 25.0
  occdist_scale: 0.1
  forward_point_distance: 0.325
  stop_time_buffer: 0.6
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : false
