global_costmap:

# Coordinate frame and tf parameters
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.8

# Rate parameters
  update_frequency: 5.0
  publish_frequency: 5.0

# Map management parameters
  static_map: true

