local_costmap:

# Coordinate frame and tf parameters
  global_frame: odom
  robot_base_frame: base_footprint
  transform_tolerance: 0.5

# Rate parameters
  update_frequency: 5.0
  publish_frequency: 5.0

# Map management parameters
  static_map: false  
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05


  
